<a href="https://colab.research.google.com/github/Imtiaj-Sajin/Computer-Vision-Pattern-Recogition/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**

**Arrays**

In [ ]:
import numpy as np


a = np.array([1, 5,6, 3])   # Rank 1 array/Vector
print(type(a))

print(a.shape) #For vector it returns (Number of Elements,nothing)

print(a[0],a[1],a[3])

print(a)
a[0]=5
a[2]=5
a[3]=5

print(a)

b=np.array([[1,2,3,8],[9,8,4,0]]) #Rank 2 array/Matrix

print(b)
print(b.shape) #For Matrix it returns: (Rows,Columns)
print(b[1,3])

<class 'numpy.ndarray'>
(4,)
1 5 3
[1 5 6 3]
[5 5 5 5]
[[1 2 3 8]
 [9 8 4 0]]
(2, 4)
0


### **Creating Different Array**

In [ ]:
a=np.zeros((3,2))
print(a)
print(a.shape)

b = np.ones((2,2))
print(b)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
(3, 2)
[[1. 1.]
 [1. 1.]]


In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

[1 4 5]
